# Generated by Django 4.2.16 on 2024-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contects'),
    ]

    operations = [
        migrations.AddField(
            model_name='contects',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
